"""Initial Migration

Revision ID: 868d199153b8
Revises: 7cbb512c7350
Create Date: 2018-01-31 15:26:47.878742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868d199153b8'
down_revision = '7cbb512c7350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
